### ISSUE TITLE
Streamlining

### ISSUE THREAD

**Issue by morgansliman** [spotitube-team/SpotiTube#59]
- [x] Scrolling text in side nav should start scrolling from current location, not restart and scroll in from left
- [x] Find good, cross-browser solution to styling scrollbars because they stand out like a sore thumb on Windows

Feel free to add new TODO's as you notice them, and check the boxes when you've completed one.

**Comment by tachprime** [comment]
The side bar stuff is driving me crazy. I'm trying to figure out why sometimes it will trigger with some containers and not others. In order to get the youtube grid to have the plugin show up I may have to convert it to a table.   I did eventually find a setting for dynamic content with the custom scroll plugin but it doesn't seem to work at all
